### ISSUE TITLE
Things to do for v3.0.0

### ISSUE THREAD

**Issue by swashata** [micc83/fontIconPicker#45]
After completion of #44 we need to do a few more things before release.

- [x] Document #16 - better repositioning.
- [x] Document #39 - Render function.
- [x] Add searchPlaceholder and extraClass support #21
- [x] Fix issue #10
